### ISSUE TITLE
360性能官方控制台未查询到数据

### ISSUE THREAD

**Issue by wanggang0813** [Qihoo360/ArgusAPM#10]
尊敬的项目Owner，

      感谢拥抱开源！
      发现一个问题，注册了一个工程，本地日志已经提示植入成功，但是从控制台未查询到相关数据。
      是未开放数据入口吗？还是客户端上报有什么规则？

谢谢解答

**Comment by bnotebook** [comment]
如果使用DC平台，数据到第二天上午就可以看到了
