### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by sososeen09** [Qihoo360/ArgusAPM#12]
运行Sample工程进入TestActivity，报错
android.view.InflateException: Binary XML file line #2: Error inflating class android.support.constraint.ConstraintLayout

**Comment by artharyoung** [comment]
> 运行Sample工程进入TestActivity，报错
> android.view.InflateException: Binary XML file line #2: Error inflating class android.support.constraint.ConstraintLayout

 try     implementation 'com.android.support.constraint:constraint-layout:1.1.3'

**Comment by akathink** [comment]
Hi，已经将ConstraintLayout的类更改为其他的布局类了。

**Comment by akathink** [comment]
> > Hi，已经将ConstraintLayout的类更改为其他的布局类了。
> 
> ok，这种报错我在本地也可以解决，把问题反馈出来还是希望这个项目不要因为一点瑕疵影响使用者的体验，为ArgusAPM开源贡献一点微薄之力

嗯嗯，非常感谢！
