### ISSUE TITLE
setApmid() 里填什么？

### ISSUE THREAD

**Issue by palorotolo** [Qihoo360/ArgusAPM#2]

**Comment by akathink** [comment]
apmid(appkey)名称必须保证唯一性，由Argus APM统一分配，请勿随意填写。

申请地址：https://dc.360.cn/product/apm

@palorotolo

**Comment by akathink** [comment]
> _No description provided._

apmid(appkey)名称必须保证唯一性，由Argus APM统一分配，请勿随意填写。

申请地址：https://dc.360.cn/product/apm
