### ISSUE TITLE
依赖加入，编译运行报错

### ISSUE THREAD

**Issue by dicallc** [Qihoo360/ArgusAPM#3]
```
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/umeng/message/UmengNotificationClickHandler;
```

**Comment by akathink** [comment]
> ```
>   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/umeng/message/UmengNotificationClickHandler;
> ```

Hi,可以尝试将友盟的SDK给排除掉：
具体操作方法如下，更详细的文档请查看[详细集成文档](https://github.com/Qihoo360/ArgusAPM/wiki/%E7%A7%BB%E5%8A%A8%E6%80%A7%E8%83%BD%E7%9B%91%E6%8E%A7-SDK-%E8%AF%A6%E7%BB%86%E9%9B%86%E6%88%90%E6%96%87%E6%A1%A3)

apply plugin: 'argusapm'

argusApmAjxConfig
 {
    exclude 'com.qihoo360.xxx' // 跳过 com.qihoo360.xxx包下的所有文件
}

将上面的com.qihoo360.xxx替换成友盟的包名即可，如果还有其他的话，请及时反馈，也可以直接在官方QQ群里咨询。

**Comment by dicallc** [comment]
1）在主项目build.gradle同级目录下，新增argusapm.gradle文件，内容如下：

apply plugin: 'argusapm'

argusApmAjxConfig
 {
    exclude 'com.qihoo360.xxx' // 跳过 com.qihoo360.xxx包下的所有文件
    excludeJar 'libammsdk'	// 跳过 libammsdk.jar
}
2）将app的build.gradle中的apply plugin: ‘argusapm’ 修改为apply from: ‘argusapm.gradle’。


按照上面步骤走：
```
argusApmAjxConfig
    {
      exclude 'com.umeng.message' // 跳过 com.qihoo360.xxx包下的所有文件
    }
```
关键是我是运行时候直接报错了...而且
argusapm.gradle (系统找不到指定的文件。)
这个应该是个文件吧

**Comment by akathink** [comment]
> 1）在主项目build.gradle同级目录下，新增argusapm.gradle文件，内容如下：
> 
> apply plugin: 'argusapm'
> 
> argusApmAjxConfig
> {
> exclude 'com.qihoo360.xxx' // 跳过 com.qihoo360.xxx包下的所有文件
> excludeJar 'libammsdk'	// 跳过 libammsdk.jar
> }
> 2）将app的build.gradle中的apply plugin: ‘argusapm’ 修改为apply from: ‘argusapm.gradle’。
> 
> 按照上面步骤走：
> 
> ```
> argusApmAjxConfig
>     {
>       exclude 'com.umeng.message' // 跳过 com.qihoo360.xxx包下的所有文件
>     }
> ```
> 关键是我是运行时候直接报错了...而且
> argusapm.gradle (系统找不到指定的文件。)
> 这个应该是个文件吧

对的，新建一个argusapm.gradle文件（和APP的build.gradle在同一个目录下），然后在该文件里配置：

`apply plugin: ‘argusapm’
argusApmAjxConfig
{
      exclude 'com.umeng.message' // 跳过 com.qihoo360.xxx包下的所有文件
}`

将app的build.gradle中的apply plugin: ‘argusapm’ 修改为apply from: ‘argusapm.gradle’即可。

如果还有问题可以直接在QQ群里咨询，这样会比较快速的解决您的问题。

**Comment by akathink** [comment]
将友盟SDK给过滤掉即可，即：
exclude 'com.umeng', 'com.alibaba', 'com.ta', 'com.ut'

**Comment by akathink** [comment]
将友盟SDK给过滤掉即可，即：
exclude 'com.umeng', 'com.alibaba', 'com.ta', 'com.ut'
