### ISSUE TITLE
wiki写的不好，看半天没看懂五个module是啥

### ISSUE THREAD

**Issue by hfutgl** [Qihoo360/ArgusAPM#43]
wiki写的不好，看半天没看懂五个module是啥？

ActivityTask输出是啥？ 报问题的机制原理完全没有

**Comment by akathink** [comment]
Module的主要是两方面的原因：
1. 为了功能独立，因为并不是所有的用户都想使用所有的功能；
2. 有些用户为了数据的保密性，需要上传到自己的服务器，所以划分网络模块；
