### ISSUE TITLE
悬浮窗不显示

### ISSUE THREAD

**Issue by liuleshuai** [Qihoo360/ArgusAPM#46]
接入SDK后，悬浮窗没有显示啊，如何开启，还是现在去掉了？

**Comment by liuleshuai** [comment]
项目比较大 ，引入的三方库很多，根据教程接入SDK，报以下错误
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow","sources":[{}]}，根据 FAQ12，修改后能够运行项目，log打印显示接入成功，但是没有任何数据输出，包括悬浮窗。。。

**Comment by liuleshuai** [comment]
Matrix那边见吧，这个库废了

**Comment by akathink** [comment]
@liuleshuai 悬浮窗那个有版本限制，最好直接查看数据库里面的数据。
