### ISSUE TITLE
集成后没有数据

### ISSUE THREAD

**Issue by DysaniazzZ** [Qihoo360/ArgusAPM#48]
根据[三分钟快速接入](https://github.com/Qihoo360/ArgusAPM/wiki/%E4%B8%89%E5%88%86%E9%92%9F%E5%BF%AB%E9%80%9F%E6%8E%A5%E5%85%A5)的文档集成，发现编译不成功，我看有好多对应的 issue 还没有解决。于是我就根据 [FAQ ](https://github.com/Qihoo360/ArgusAPM/wiki/FAQ) 里第 12 条，按照一般的依赖库集成，集成后运行没问题，也有对应标识集成成功的日志，但是数据库里基本没什么数据。

测试手机：小米4，Android 6.0
集成版本：3.0.1.1001

测试生成的数据库：

[apm.db.zip](https://github.com/Qihoo360/ArgusAPM/files/3595393/apm.db.zip)

**Comment by akathink** [comment]
@DysaniazzZ 这是因为没有配置云规则文件，目前暂不对外提供服务了，需要使用者自己开发一个云规则下发的后台。我们已经提供好了接口，可以直接实现即可。
