### ISSUE TITLE
transformClassesWithDexForDebug

### ISSUE THREAD

**Issue by dede1314** [Qihoo360/ArgusAPM#8]
因为为了更加方便debug,不想通过gradle插件的方式引入。
按照下面的方式修改
`apply plugin: 'com.android.application'

//apply from: 'argusapm.gradle'
`
........

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.squareup.okhttp3:okhttp:3.10.0'
    compile project (':argus-apm-main')
    compile project (':argus-apm-okhttp')
    compile project (':argus-apm-cloud')
    compile project (':argus-apm-cloud-dummy-impl')
    compile project (':argus-apm-aop')
}

 但是现在编译报错，日志如下：
* What went wrong:
Execution failed for task ':argus-apm-sample:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/argusapm/android/network/IUpload;

**Comment by dede1314** [comment]
暂时注释掉cloud 相关的两个project(argus-apm-cloud,argus-apm-cloud-dummy-impl)。 现在可以运行，功能应该缺失....

**Comment by akathink** [comment]
Hi， @dede1314 ,如果想要通过源码的方式接入，请参考：[FAQ 第十条](https://github.com/Qihoo360/ArgusAPM/wiki/FAQ)
